# -*- coding: utf-8 -*-
"""Generate_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AqehrCGsarFVnLsyzNuYpLZF6vSSax01
"""

!pip install SimpleITK

import SimpleITK as sitk
import numpy as np

inputImage = sitk.ReadImage("name.nii.gz")

"""Generate Inverted MRI"""
invert = sitk.InvertIntensityImageFilter()
img = invert.Execute(inputImage)

sitk.WriteImage(img, "name_inv.nii.gz")


"""Clip noise"""

# Convert the image to a numpy array
image_array = sitk.GetArrayFromImage(inputImage)

# Define the mean and standard deviation for the Gaussian noise
mean = 0
stddev = 25  # Adjust as necessary

# Generate Gaussian noise
noise = np.random.normal(mean, stddev, image_array.shape)

# Add the noise to the image
noisy_image_array = image_array + noise

# Ensure the pixel values are within the valid range
# Assuming the image is 8-bit, clip values to be in the range [0, 255]
noisy_image_array = np.clip(noisy_image_array, 0, 255)

# Convert the noisy image back to a SimpleITK image
noisy_image = sitk.GetImageFromArray(noisy_image_array.astype(np.uint8))
noisy_image.CopyInformation(inputImage)


# Save the noisy image
sitk.WriteImage(noisy_image, 'name_clip.nii.gz')

